# Exploring code speed


## How execution time scales

### Carrying capacity
```{r,echo=F}
doit=FALSE
```
```{r,eval=!doit}
load("data/allstr.bin")
load("data/allstr_tstep.bin")
```


Testing how execution time  change  when K increase when no social learn vs random selection vs best selection:
General parameters:
```{r}
strategies=c("best","random","fitprop")
names(strategies)=strategies
colsstrategies=c("red","blue","green")
names(colsstrategies)=strategies
Ks=c(100,500,1000,2000)
tstep=500
n=300
o=0 #omega
d=1 #delta
m=c(x=.1,y=.1,z=.1)
mu=c(x=.001,y=0.001,z=0.001)
E=c(x=0,y=0,z=0)
sigma=c(s=10,y=10,z=10)
tsteps=c(100,1000,2000,4000)
```

```{r,eval=doit}
library(microbenchmark)
pop=generatePop(n,distrib=list(x=runif(n,-1,1),y=runif(n),z=runif(n)),df=F)

allstr=lapply( strategies,function(strat)
              {
                  timings=lapply(Ks,function(k)
								 {
									 print(k)
									 microbenchmark(
													evosolearn(
																   n=n,
																   tstep=tstep,
																   omega = o,
																   delta = d ,
																   b=2,
																   K=k,
																   m=m,
																   mu=mu,
																   E=E,
																   sigma=sigma,
																   sls=strat,
																   pop=pop,
																   outputrate=1000,log=T
																   ),
													times=5,
													unit="s")
									 
								 })
                  print(strat)
                  sapply(timings,function(i)mean(i[,"time"]))
              }
)

save(file="data/allstr.bin",allstr)
```


```{r profileKs,fig.cap="Executation time for differente carrying capacities"}
allstr=lapply(allstr,"/",10000000000)
plot(1,1,ylim=range(allstr),xlim=range(Ks),type="l",ylab="Execution time (in second)",xlab="K")
na=lapply(strategies,function(f)lines(Ks,allstr[[f]],col=colsstrategies[f]))
legend("topleft",legend=strategies,lty=1,col=colsstrategies)
```

### Number of time step 

Looking at the nubmer of timestep:

```{r,eval=doit}
k=500

pop=generatePop(n,distrib=list(x=runif(n,-1,1),y=runif(n),z=runif(n)),df=F)

allstr_tstep=lapply( strategies,function(strat)
              {
                  timings=lapply(tsteps,function(tstep)
                                 microbenchmark(
                                                evosolearn(
                                                               n=n,
                                                               tstep=tstep,
                                                               omega = o,
                                                               delta = d ,
                                                               b=2,
                                                               K=k,
                                                               m=m,
                                                               mu=mu,
                                                               E=E,
                                                               sigma=sigma,
                                                               sls=strat,
                                                               pop=pop,
                                                               outputrate=10,log=F
                                                               ),
                                                times=5,
                                                unit="s")
                                 )
                  print(strat)
                  sapply(timings,function(i)mean(i[,"time"]))
              }
)
save(file="data/allstr_tstep.bin",allstr_tstep)
```

```{r profileTstep,fig.cap="Execution time for different number of tstep"}
allstr_tstep=lapply(allstr_tstep,"/",10000000000)
plot(1,1,ylim=range(allstr_tstep),xlim=range(Ks),type="l",ylab="Execution time (in second)",xlab="time step")
na=lapply(strategies,function(f)lines(Ks,allstr_tstep[[f]],col=colsstrategies[f]))
legend("topleft",legend=strategies,lty=1,col=colsstrategies)
```

## Profiling function calls

Profiling the model using `Rprof`:


```{r expCountCall,fig.show="hold",fig.cap="Short expe",out.width="45%"}
n=1000
pop=generatePop(n,distrib=list(x=runif(n,-1,1),y=rep(1,n),z=rep(1,n)),df=F)
tstep=1000
theta=environment(tstep,2,0)
listallprof=list()
for(strat in  strategies){
    df = "test.log"
    Rprof(df, memory.profiling = TRUE)
    evodf=evosolearn(b=2,K=100,m=m,mu=mu,E=E,sigma=sigma,log=F,sls=strat,theta=theta,pop=pop)
    Rprof(NULL) ; 
    sdf=summaryRprof(df)
    listallprof[[strat]]=sdf$by.self
    plotResults(evodf,statvar=c("x","y","z"),theta=F,addrgb=F)
}
```
```{r}
    knitr::kable(listallprof[[1]])
```
```{r}
    knitr::kable(listallprof[[2]])
```
