# Environment Generator and noise-color properties


## Check color of noise: 

Quic exploration of function used to generate $\frac{1}{f}$-noise:

```{r slope,fig.cap="noise generator"}
par(mfrow=c(3,2))
t=1000 #number of timestep
par(mfrow=c(3,2),mar=c(2,2,1,1))
for(alpha in 0:2){ #alpha as used in YK95 as our $\omega$
    ts=TK95(t,alpha) #generate random noise following Timmer & Koenig (1995) implemented in tuner package(https://rdrr.io/cran/tuner/src/r/waveforms.r)
    plot(ts,type="l") #plot the environment
    y=getSpectrum(ts) #get spectrum of the environment generated
    x=1:length(y)
    plot(log(x),log(y))
    fit=lm(log(y)~log(x),cbind.data.frame(x=1:length(y),y=y)) #fit a linear model to check slope
    abline(fit,col="red") #visualise the fit and coefficient computed
    text(1,max(log(y)),paste("coef=",abs(round(fit$coefficients[2],2))),col="red")
}
```

## Check $\delta$ (variance) of noise

```{r ,fig.cap="enrivonment generator"}
par(mfrow=c(3,2))
t=1000 #number of timestep
par(mfrow=c(3,2),mar=c(2,2,1,1))
for(omega in 0:2){ 
    ts=environment(t,omega=omega,delta=0.1)
    plot(ts,type="l") #plot the environment
    y=getSpectrum(ts) #get spectrum of the environment generated
    x=1:length(y)
    plot(log(x),log(y))
    fit=lm(log(y)~log(x),cbind.data.frame(x=1:length(y),y=y)) #fit a linear model to check slope
    abline(fit,col="red") #visualise the fit and coefficient computed
    text(1,max(log(y)),paste("coef=",abs(round(fit$coefficients[2],2))),col="red")
}
```


## Check auto-correlation

Using the same function we can have different level of auto-correlation 

```{r cov,fig.cap="autocorrelation"}
    par(mfrow=c(1,3))

    for(omega in 0:2){
        t=environment(50000,omega,.1)
        vtm=t[1:(length(t)-1)]
        vt=t[2:length(t)]
        print(cov(vt,vtm))
        cv=round(cov(vt,vtm),digit=3)
        plot((1:50000)[seq(1,50000,100)],t[seq(1,50000,100)],main=bquote(omega == .(omega)~","~delta==.1~", cov("*theta[t]*","*theta[t-1]*")" == .(cv)),ylab=bquote(theta[t]),,xlab="t",type="l",lwd=1)
    }

```

## Real Environments

There is lot of dataset available that  can gives us  stuff

```{r loadRealEnv,eval=F}
    #ngripR=read.csv("data/ngripRAW.csv")
    #ngrip$year=-(ngripR$years.BP.2000)
    #ngrip$dOice=ngripR$permille #delta 18 O ice from greenland
    #ngrip=as.data.frame(ngrip)
    #ngrip=ngrip[order(ngrip$year),]
    #write.csv(file="data/ngrip.csv",ngrip,row.names=F)
    ngrip=read.csv("data/ngrip.csv")

    #lr04R=read.csv("data/lr04RAW.csv")
    #lr04$year=-(lr04R$years.BP.2000*1000)
    #lr04$Ts=convertEpstein(lr04R$permille) #conert d18O to temperature using epstein 71
    #lr04$dOsea=lr04R$permille #delta 18 O ice from bentic drill  
    #lr04=as.data.frame(lr04)
    #lr04=lr04[order(lr04$year),]
    #write.csv(file="data/lr04.csv",lr04,row.names=F)
    lr04=read.csv("data/lr04.csv")

    #ls16R=read.csv("data/ls16RAW.csv")
    #ls16$year=-(ls16R$years.BP.2000*1000)
    #ls16$Ts=convertEpstein(ls16R$permille) #conert d18O to temperature using epstein 71
    #ls16$dOsea=ls16R$permille #delta 18 O ice from bentic drill  
    #ls16=as.data.frame(ls16)
    #ls16=ls16[order(ls16$year),]
    #write.csv(file="data/ls16.csv",ls16,row.names=F)
    ls16=read.csv("data/ls16.csv")

    #vostokR=read.csv("data/vostokRAW.csv")
    #vostok$year=-(vostokR$Ice.age..GT4.)
    #vostok$dD=vostokR$deut #delta D deuterium
    #vostok$dTs=vostokR$deltaTS #delta Temperature surface 
    #vostok=as.data.frame(vostok)
    #vostok=vostok[order(vostok$year),]
    #write.csv(file="data/vostok.csv",vostok,row.names=F)
    vostok=read.csv("data/vostok.csv")

    #epicaR=read.csv("data/epica04RAW.csv")
    #epica$year=-(epicaR$Meanage.yrBP)
    #epica$dD=epicaR$deltaD.permill #delta D deuterium
    #epica=as.data.frame(epica)
    #epica=epica[order(epica$year),]
    #write.csv(file="data/epica.csv",epica,row.names=F)
    epica=read.csv("data/epica.csv")
par(mfrow=c(3,1))

 # rescale all temperature differences  using vostok temperature
for(env in namesRealEnv[-4]){
    i=get(env)
    env="lr04"
    oldestDate=max(min(vostok$year,na.rm=T),min(i$year,na.rm=T))
    ri=range(i[ i$year>oldestDate ,2]) 
    rv=range(vostoku$dTs[ vostoku$year>oldestDate])
    i$dTsVscales=(rv[2]-rv[1])/(ri[2]-ri[1])*(i[,2]-ri[2])+rv[2]
    write.csv(file=paste0("data/",env,".csv"),i,row.names=F)
    plot(i$year,i$dTsVscales,type="o",pch=20,main=env,ylab=expression(delta*T[vscale]),xlab="year")
    points(vostok$year,vostok$dTs,col="red",type="o",pch=20)
}


    #plot(ngripSubsample[match((ls16$years.BP.2000*1000),ngripSubsample$years.BP.2000,nomatch=FALSE),"permille"],-ls16$permille[2:246])
    #ngrip=ngrip[c(seq(1,nrow(ngrip),2),nrow(ngrip)),]
    namesRealEnv=c("epica","lr04","ls16","vostok")
    namesFun=c("getMean","getLast","getFirst")

    combiname=expand.grid(namesRealEnv,namesFun)

    allRealEnv=lapply(namesRealEnv,function(i)assign(i,read.csv(paste0("data/",i,".csv")),pos=.GlobalEnv))
    names(allRealEnv)=namesRealEnv
    lapply(allRealEnv,range)
    lapply(allRealEnv,function(i)max(getDateResolution(i$year)))

```

```{r}

env="epica"
dates=getDateResolution(get(env)$year)
plot(density(dates,from=min(dates),to=max(dates),bw=1),log="x")

i=get(env)
freq_max=abs(min(i$year)/max(getDateResolution(i$year)))
i$yearSample=cut(i$year,breaks=freq_max)
plot(i$year,i$dTsVscales)
points(applySampling(i$yearSample,i$year,getMean),applySampling(i$yearSample,i$dTsVscales,getMean),col="blue")
points(applySampling(i$yearSample,i$year,getFirst),applySampling(i$yearSample,i$dTsVscales,getFirst),col="green")
points(applySampling(i$yearSample,i$year,getLast),applySampling(i$yearSample,i$dTsVscales,getLast),col="red")

```


