


# Exploring Real Environment

Using data available here from this paper: https://www.nature.com/articles/nature02805

The color used in he following graphs follow the scale described before: 


```{r echo=FALSE, message=FALSE}
slpalette=colorRampPalette(c(rgb(0,.5,0),rgb(0,.5,1)))
ilpalette=colorRampPalette(c(rgb(0,.5,0),rgb(1,.5,0)))
survivalpallette=colorRampPalette(c("grey","yellow","dark green"))
extinctpalette=colorRampPalette(c("chartreuse","white"))
pureSl=slpalette(2)[2]
pureIl=ilpalette(2)[2]

environment=read.csv("data/theta_real.csv")
binded=do.call("rbind",lapply(list.files(path="exploreRealEnvBESTfull",recursive=T,full.names=T,pattern="*cross*"),function(u){load(u);return(binded)}))

plotMatrixStrateAndEn <- function(sum_mat,environment){
    pureIl=rgb(1,.5,0)
    pureSl=rgb(0,.5,1)
    mixed=rgb(1,.5,1)
    par(fig=c(0,1,.8,1),mar=rep(0,4),oma=c(2,2,1,1))
    plot(environment$permille,col="dark green",lwd=1,type="l",axes=F)
    par(new=T)
    plotTres(sum_mat$mean_x,ylim=range(sum_mat$mean_x,na.rm=T))
    mtext(expression(theta),4,0,col="dark green")
    mtext(expression(bar(x)),2,0,col="1")
    par(fig=c(0,1,0,.8),new=T)
    plotTres(sum_mat$prop_y,col=pureIl,ylim=c(0,1))
    par(new=T)
    plotTres(sum_mat$prop_z,col=pureSl,ylim=c(0,1))
    par(new=T)
    plotTres(sum_mat$prop_yz,col=mixed,ylim=c(0,1))
    axis(1);axis(2);box()
}


plotTres <- function(u,col=1,...){
    plot(u[2,],col=col,axes=F,type="l",...)
    lines(u[1,],col=col,lty=3,lwd=.8)
    lines(u[3,],col=col,lty=3,lwd=.8)
}
```
```{r echo=F,asi}
mt=matrix(NA,nrow=unique(binded$mu),ncol=unique(binded$m))
i=1
for(mu in rev(unique(binded$mu))){
    for(m in unique(binded$m)){
        mta
    }
}
```


